#!/bin/bash
# Run clang-tidy over the RepRapFirmware sources for one board configuration
# By default this looks for class members that a constructor leaves uninitialised
#
# The build uses arm-none-eabi-gcc, so the compile commands need adjusting before clang can parse them:
#  - GCC-only options that clang rejects are removed from the compile database
#  - GCC's newlib and libstdc++ include directories are passed explicitly
#  - uint32_t/int32_t are made 'long' types as they are in arm-none-eabi-gcc, otherwise overloads in CoreN2G clash
#  - -Werror from the makefiles is overridden, because clang warns about things that GCC does not
#  - static_assert is disabled, because clang cannot evaluate the strlen/strcmp calls in some of them as GCC does,
#    and the static analyser skips any file that has a compiler error
#
# Requires: bear, clang-tidy (which provides run-clang-tidy), jq

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
RRF_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

# clang-analyzer-optin.cplusplus.UninitializedObject is not included because it ignores objects created with 'new',
# which is how kinematics, sensors, heaters etc. are created
DEFAULT_CHECKS='-*,cppcoreguidelines-pro-type-member-init'

BOARD="Duet3_MB6HC"
CHECKS="$DEFAULT_CHECKS"
JOBS=$(nproc)
REGENERATE=0
IGNORE_ARRAYS=0

usage() {
	cat <<EOF
Usage: $(basename "$0") [options] [file-regex]

Runs clang-tidy over every source file whose path matches file-regex
(default: all C++ files under src/).

Options:
  -b BOARD    Board configuration to analyse (default: $BOARD)
  -r          Regenerate the compile database. This cleans and rebuilds BOARD under bear.
              Needed on the first run, and after adding or removing source files.
  -c CHECKS   clang-tidy checks (default: $DEFAULT_CHECKS)
  -a          Ignore arrays in cppcoreguidelines-pro-type-member-init, which reduces false positives
              from arrays that are filled element by element in the constructor body
  -j JOBS     Number of parallel clang-tidy processes (default: $JOBS)
  -h          Show this help

Output goes to clang-tidy-out/BOARD/:
  tidy.log            full clang-tidy output
  tidy-warnings.txt   unique warnings, one per line

Examples:
  $(basename "$0") -r                                   # first run
  $(basename "$0") 'src/Movement/Kinematics/.*\.cpp$'   # just the kinematics
  $(basename "$0") -b Duet3Mini5plus -r                 # Mini 5+ specific code
EOF
}

while getopts "b:rc:aj:h" opt; do
	case "$opt" in
		b) BOARD="$OPTARG" ;;
		r) REGENERATE=1 ;;
		c) CHECKS="$OPTARG" ;;
		a) IGNORE_ARRAYS=1 ;;
		j) JOBS="$OPTARG" ;;
		h) usage; exit 0 ;;
		*) usage >&2; exit 1 ;;
	esac
done
shift $((OPTIND - 1))

# C files are excluded by default because the libstdc++ include directories added below are only valid for C++
FILE_REGEX="${1:-$RRF_ROOT/src/.*\.cpp$}"

for tool in bear clang-tidy run-clang-tidy jq; do
	if ! command -v "$tool" >/dev/null; then
		echo "ERROR: $tool not found. Install it with: sudo apt-get install -y clang-tidy bear jq" >&2
		exit 1
	fi
done

OUT_DIR="$RRF_ROOT/clang-tidy-out/$BOARD"
RAW_DB="$OUT_DIR/compile_commands.raw.json"
mkdir -p "$OUT_DIR"

cd "$RRF_ROOT"

# Step 1: record the compile commands. Bear only sees files that are actually compiled, so the board is cleaned first.
if [ "$REGENERATE" = 1 ] || [ ! -f "$RAW_DB" ]; then
	echo "Generating compile database for $BOARD (clean rebuild)..."
	make clean-"$BOARD"
	bear --output "$RAW_DB" -- make "$BOARD" -j"$JOBS"
fi

# Step 2: remove options that clang does not accept. run-clang-tidy expects the file to be called compile_commands.json.
jq 'map(.arguments |= map(select(. != "-mfp16-format=ieee")))' "$RAW_DB" > "$OUT_DIR/compile_commands.json"

# Step 3: ask the cross-compiler for its system include directories, using the board's CPU options
COMPILER=$(jq -r '[.[] | select(.file | endswith(".cpp"))][0].arguments[0]' "$RAW_DB")
if [ -z "$COMPILER" ] || [ "$COMPILER" = "null" ]; then
	echo "ERROR: no C++ files in $RAW_DB. Run again with -r to regenerate it." >&2
	exit 1
fi
mapfile -t CPU_FLAGS < <(jq -r '[.[] | select(.file | endswith(".cpp"))][0].arguments[]
								| select(test("^-m(cpu|fpu|float-abi)=") or . == "-mthumb")' "$RAW_DB")
mapfile -t SYSTEM_INCLUDES < <(echo | "$COMPILER" "${CPU_FLAGS[@]}" -xc++ -E -Wp,-v - 2>&1 \
								| sed -n '/<...> search starts/,/End of search/{/^ /p}' | sed 's/^ *//')
if [ ${#SYSTEM_INCLUDES[@]} = 0 ]; then
	echo "ERROR: could not get the system include directories from $COMPILER" >&2
	exit 1
fi

# Step 4: make clang's 32-bit integer types match arm-none-eabi-gcc's
COMPAT_HEADER="$OUT_DIR/arm-gcc-compat.h"
cat > "$COMPAT_HEADER" <<'EOF'
// Generated by Scripts/run-clang-tidy.sh
// arm-none-eabi-gcc defines int32_t/uint32_t as long types, clang defines them as int types
#undef __INT32_TYPE__
#define __INT32_TYPE__ long int
#undef __UINT32_TYPE__
#define __UINT32_TYPE__ long unsigned int
#undef __INT_LEAST32_TYPE__
#define __INT_LEAST32_TYPE__ long int
#undef __UINT_LEAST32_TYPE__
#define __UINT_LEAST32_TYPE__ long unsigned int
#undef __INT32_C
#define __INT32_C(c) c ## L
#undef __UINT32_C
#define __UINT32_C(c) c ## UL

// GCC can evaluate strlen and strcmp in a static_assert, clang cannot. Any compiler error stops the static analyser
// from running on that file, so the assertions are disabled here. The real GCC build still checks them.
#ifdef __cplusplus
# define static_assert(...) static_assert(true, "")
#endif
EOF

# Step 5: write the clang-tidy configuration. A config file avoids shell quoting problems with the extra arguments.
CONFIG_FILE="$OUT_DIR/clang-tidy.yaml"
{
	echo "Checks: '$CHECKS'"
	echo "HeaderFilterRegex: '^$RRF_ROOT/src/'"
	if [ "$IGNORE_ARRAYS" = 1 ]; then
		echo "CheckOptions:"
		echo "  cppcoreguidelines-pro-type-member-init.IgnoreArrays: true"
	fi
	echo "ExtraArgs:"
	echo "  - '--target=arm-none-eabi'"
	echo "  - '-Wno-error'"
	echo "  - '-Wno-unknown-warning-option'"
	echo "  - '-Wno-unused-command-line-argument'"
	echo "  - '-Wno-ignored-optimization-argument'"
	echo "  - '-ferror-limit=0'"
	echo "  - '-include$COMPAT_HEADER'"
	for dir in "${SYSTEM_INCLUDES[@]}"; do
		echo "  - '-isystem$dir'"
	done
} > "$CONFIG_FILE"

# Step 6: run clang-tidy. It exits with an error status if any file had compiler errors, see below.
LOG="$OUT_DIR/tidy.log"
WARNINGS="$OUT_DIR/tidy-warnings.txt"
echo "Running clang-tidy on files matching: $FILE_REGEX"
set +e
run-clang-tidy -p "$OUT_DIR" -config-file="$CONFIG_FILE" -j"$JOBS" -quiet "$FILE_REGEX" > "$LOG" 2>&1
TIDY_STATUS=$?
set -e

# A header is reported once for each file that includes it, so remove duplicates
DIAGNOSTIC='^[^ ]+:[0-9]+:[0-9]+: '
grep -E "$DIAGNOSTIC"'warning: .*\[[a-z0-9.,-]+\]$' "$LOG" | sed "s|^$RRF_ROOT/||" | sort -u > "$WARNINGS" || true

# Some files use GCC extensions that clang rejects. clang-tidy still checks the rest of those files,
# but clang-analyzer-* checks skip any file with an error.
ERRORS=$(grep -E "$DIAGNOSTIC"'error: ' "$LOG" | sed "s|^$RRF_ROOT/||" | sort -u || true)
ERROR_FILES=$(awk '/^clang-tidy[-0-9]* /{f=$NF} /^[^ ]+:[0-9]+:[0-9]+: error: /{print f}' "$LOG" | sort -u | sed "s|^$RRF_ROOT/||")

echo
echo "Unique warnings: $(wc -l < "$WARNINGS")  ->  ${WARNINGS#"$RRF_ROOT"/}"
echo "Full log:                     ${LOG#"$RRF_ROOT"/}"
if [ -n "$ERRORS" ]; then
	echo
	echo "Note: clang reported $(echo "$ERRORS" | wc -l) compiler errors in these files, mostly GCC extensions it does not support."
	echo "clang-tidy checks still ran on the rest of each file; clang-analyzer-* checks were skipped for them."
	echo "$ERROR_FILES" | sed 's/^/  /'
elif [ "$TIDY_STATUS" != 0 ]; then
	echo
	echo "WARNING: run-clang-tidy exited with status $TIDY_STATUS, see the log"
fi
