name: Upload prerelease assets

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Download release assets
      - name: Download assets
        run: |
          mkdir assets
          cd assets
          gh release download -R Duet3D/RepRapFirmware $GITHUB_REF_NAME -p "*.bin" -p "*.uf2"
        env:
          GH_TOKEN: ${{ github.token }}

      # Clean up unused files
      - name: Remove unused files
        run: |
          cd assets
          rm -f Duet2CombinedFirmware.bin DuetMaestroFirmware.bin Duet*_SD*.bin Duet3_CAN*.bin DuetWiFi*.bin

      # Upload assets to unstable feed on pkg.duet3d.com
      - name: Upload files to unstable package feed
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: pkg.duet3d.com
          port: 22
          username: ${{ secrets.PKG_SSH_USER }}
          password: ${{ secrets.PKG_SSH_PASS }}
          privateKey: ${{ secrets.PKG_SSH_KEY }}
          localPath: ./assets
          remotePath: /var/rrf-pkg/unstable

      # Upload assets to unstable-3.4 feed on pkg.duet3d.com
      - if: contains(github.ref, '3.4')
        name: Upload files to unstable 3.4 feed
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: pkg.duet3d.com
          port: 22
          username: ${{ secrets.PKG_SSH_USER }}
          password: ${{ secrets.PKG_SSH_PASS }}
          privateKey: ${{ secrets.PKG_SSH_KEY }}
          localPath: ./assets
          remotePath: /var/rrf-pkg/unstable-3.4

      # Upload assets to unstable-3.5 feed on pkg.duet3d.com
      - if: contains(github.ref, '3.5')
        name: Upload files to unstable 3.5 feed
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: pkg.duet3d.com
          port: 22
          username: ${{ secrets.PKG_SSH_USER }}
          password: ${{ secrets.PKG_SSH_PASS }}
          privateKey: ${{ secrets.PKG_SSH_KEY }}
          localPath: ./assets
          remotePath: /var/rrf-pkg/unstable-3.5

      # Upload assets to unstable-3.6 feed on pkg.duet3d.com
      - if: contains(github.ref, '3.6')
        name: Upload files to unstable 3.6 feed
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: pkg.duet3d.com
          port: 22
          username: ${{ secrets.PKG_SSH_USER }}
          password: ${{ secrets.PKG_SSH_PASS }}
          privateKey: ${{ secrets.PKG_SSH_KEY }}
          localPath: ./assets
          remotePath: /var/rrf-pkg/unstable-3.6

